### PR TITLE
v1.2.8-beta.2

### PR DESCRIPTION
**Pull request by vassbo**

### CODE REVIEW

**Comment by gkiibzmultimedia** [comment]
the transitions is not working in this version

**Comment by vassbo** [comment]
@gkiibzmultimedia In my testing it works fine, make sure you have not set any custom item, or slide, or style transitions, then change the global transition to e.g. "Fade" and 0.5 seconds, and make sure that works!
bilde

**Comment by gkiibzmultimedia** [comment]
I revert back to beta 1 and the transitions are working fine.

**Comment by vassbo** [comment]
Looking more into it, apparently it's not unique to the latest pre-release as it have probably been an issue for a long time.
The same issue I think: https://github.com/ChurchApps/FreeShow/issues/353

It must be a Svelte bug, and it seems to happen like 50% of the time, so restarting the app (output window) will eventually make it work.
The strange part is that it works 100% in the development build. And like 80% of the time in the preview.

Apparently if the output window is displayed right after opening, it works more of the time I think.

**Comment by lwallace22** [comment]
video provided i see no solution to this issue

**Pull request merged**
